# Generated by Django 4.1.7 on 2023-03-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(height_field=400, upload_to='pics', width_field=400),
        ),
    ]
